server:
  port: 8080
  servlet:
    context-path: /virtual-karate-dojo-api
spring:
  profiles:
    active: ${PROFILE_ACTIVE}
  main:
    allow-circular-references: true
  config:
    name: application
    location: classpath:/,classpath:/config/,file:./,file:./config/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
