spring:
  jackson:
    default-property-inclusion: NON_NULL
  banner:
    location: classpath:banner.txt
  data:
    mongodb:
      uri: ${MONGODB_TEST_URL}
      auto-index-creation: true
  web:
    resources:
      add-mappings: true
stripe:
  secret-key: ${STRIPE_SECRET_KEY}
urls:
  frontend-url: ${FRONTEND_URL}
