name: Deploy to k3s on VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 🔄 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # ☕ 2. Configurar Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "21"

      # ⚙️ 3. Compilar el proyecto con Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 🐳 4. Construir la imagen Docker
      - name: Build Docker image
        run: docker build -t virtual-karate-dojo-api:latest .

      # 🧱 5. Guardar la imagen como tarball
      - name: Save Docker image as tarball
        run: docker save virtual-karate-dojo-api:latest > virtual-karate-dojo-api.tar

      # 🔐 6. Descifrar clave privada SSH
      - name: Decrypt SSH private key
        run: |
          gpg --batch --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
            -o ./private_key -d .github/secrets/secrets.gpg
          chmod 600 ./private_key

      # ✅ 7. Validar existencia de secretos requeridos
      - name: Validar existencia de secretos requeridos
        run: |
          if [ -z "${{ secrets.VPS_SSH_USERNAME }}" ] || [ -z "${{ secrets.VPS_SSH_HOST }}" ]; then
            echo "❌ Faltan uno o más secretos obligatorios."
            exit 1
          fi

      # 📦 8. Copiar imagen al VPS con scp
      - name: Copy Docker image tarball manually using scp
        run: |
          scp -i ./private_key -o StrictHostKeyChecking=no \
            virtual-karate-dojo-api.tar \
            ${{ secrets.VPS_SSH_USERNAME }}@${{ secrets.VPS_SSH_HOST }}:/home/${{ secrets.VPS_SSH_USERNAME }}/

      # 🚀 9. Desplegar en k3s usando el .env local del VPS
      - name: Deploy to k3s manually
        run: |
          ssh -i ./private_key -o StrictHostKeyChecking=no ${{ secrets.VPS_SSH_USERNAME }}@${{ secrets.VPS_SSH_HOST }} << 'EOF'
            # Importar la imagen al containerd de k3s
            sudo k3s ctr images import /home/${{ secrets.VPS_SSH_USERNAME }}/virtual-karate-dojo-api.tar

            # Crear o actualizar el Secret desde el .env local
            sudo kubectl create secret generic virtual-karate-dojo-env \
              --from-file=.env=/home/k3s-deployments/virtual-karate-dojo-api/.env \
              --dry-run=client -o yaml | sudo kubectl apply -f -

            # Aplicar el deployment si aún no existe o se ha actualizado
            sudo kubectl apply -f /home/k3s-deployments/virtual-karate-dojo-api/deploy-virtual-karate-dojo-api.yml

            # Reiniciar el deployment para que coja la nueva imagen y config
            sudo kubectl rollout restart deployment virtual-karate-dojo-api
          EOF

      # 🧹 10. Limpiar clave privada
      - name: Cleanup private key
        if: always()
        run: rm -f ./private_key
